image: node:18-alpine

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - npm install
    - npm test

test_job:
  stage: test
  script:
    - echo 'Running tests...'
    - npm test

