image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - dotnet restore
    - dotnet build
    - dotnet test

test_job:
  stage: test
  script:
    - echo 'Running tests...'
    - dotnet test


